# Generated by Django 4.2.20 on 2025-04-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_paid',
            field=models.BooleanField(default=False),
        ),
    ]
