# Generated by Django 4.2.20 on 2025-04-12 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_has_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='free_access_start',
            new_name='access_expires',
        ),
    ]
