# Generated by Django 4.2.20 on 2025-04-12 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_free_access_start_profile_access_expires'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='access_expires',
            new_name='free_access_start',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='has_paid',
        ),
    ]
